### ISSUE TITLE
week-1 discussion points 

### ISSUE THREAD

**Issue by gelilaa** [gelilaa/VoxBox#3]
# Today's schedule 
Topic: VoxBox week-1
Time: Dec 15, 2020 12:00 PM Amsterdam, Berlin, Rome, Stockholm, Vienna

Join Zoom Meeting
https://us04web.zoom.us/j/71033636346?pwd=RGJDeG1TbWtWZ1BhSDRJSUYyRlE1dz09

Meeting ID: 710 3363 6346
Passcode: U5tFbY

# discussion points 
1. User stories: discuss the user- stories that we have till now and select a collective and finale user story. DONE !
2. Wireframes: create a wireframe(at least a sample) and discuss over it..(we will be using Figma); will be done by @adekimpianna 

### please comment discussion points you would like to discuss about ...

# [conclusion](https://github.com/gelilaa/VoxBox/wiki/communication-week-1)

**Comment by iLienstAr** [comment]
I am looking forward to see your progress on Sunday. You are working in a very professional way. Keep going like this!

**Comment by gelilaa** [comment]
Done
