### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by yildiraykoyuncu** [gelilaa/VoxBox#49]
- [x] A navbar component to contain a logo with a link to homepage and navigation links.
- [x] A SignedOut component visible if a user is not logged in which will contain;
    - [x] SignUp link which directs to the SignUp page 
    - [x] LogIn link which directs to the Login page 
- [x] A signed in component visible if a user logged in which will contain;
    - [x] My profile link to direct user to profile page
    - [x] Log out button which will log user out

relates #15
relates #16 
relates #17

**Comment by gelilaa** [comment]
Done!!
