### ISSUE TITLE
Frontend Discussion

### ISSUE THREAD

**Issue by LujiAnna** [gelilaa/VoxBox#5]
- [Discussion on the tech stack we will be using]()

**Comment by LujiAnna** [comment]
Hey guys, 
I was thinking we use react?
Or who is up to vanilla js?
Am okay with both, but most preferably react

**Comment by LujiAnna** [comment]
Talking about components ...
Do we need some sort of a separate component wireframe for this, after we know the main features?

**Comment by yildiraykoyuncu** [comment]
I suggest using React and Redux. I think that would be a good opportunity to sharpen our React skills.

**Comment by LujiAnna** [comment]
@yildiraykoyuncu totally!!
Btw, do you have some tutorials/etc recommendations on react&redux that I can go through in the meantime ?

**Comment by yildiraykoyuncu** [comment]
@LujiAnna I watched net-ninja react-redux tutorial. It is pretty good. But he uses class components you need to convert them to hooks yourself.

**Comment by LujiAnna** [comment]
Thanks @yildiraykoyuncu, I will check it out.
Yes, I remember Shriyans mentioned that it's good to use functions instead of class going forward

**Comment by LujiAnna** [comment]
I think we should also use some css frameworks, like bootstrap or sth.
What do you think?

**Comment by yildiraykoyuncu** [comment]
Yeap we can use bootstrap or material ui. Material is more popular these days I think. But we can use any of them of course.

**Comment by LujiAnna** [comment]
I have not yet used materialUi, but I wouldn't miss the chance to do so :). So lets go with it

**Comment by LujiAnna** [comment]
@yildiraykoyuncu 
Do you think its best to use MUI using CDN or install it? 
And installing such library, is it better done locally in project or globally?

**Comment by oguzkarademir** [comment]
Guys actually I don't have good knowledge about material ui but I will be better until we start to write code.
I will follow react tutorial to be better, I am searching 🧐😃

**Comment by yildiraykoyuncu** [comment]
@LujiAnna I think best option would be install it as npm package.

**Comment by yildiraykoyuncu** [comment]
@oguzkarademir I am not very good at it as well. But we will learn :)

**Comment by dirk-jacobs** [comment]
React looks ok to me. Redux isn't exactly what you call 'light'
An alternative is to use the Context concept of React which is easy to use and in your case should do the job.

Check it out !
https://www.digitalocean.com/community/tutorials/how-to-share-state-across-react-components-with-context

**Comment by LujiAnna** [comment]
@dirk-jacobs thanks on context. I think we should definitely give it a go..
I have updated the [front-end dev-tools](https://github.com/gelilaa/VoxBox/wiki/Development-Tools) in the wiki concerning the tools.

**Comment by dirk-jacobs** [comment]
Just to inform you that 'context' is not a separate library but since version 16.x part of React itself
https://reactjs.org/docs/context.html#gatsby-focus-wrapper

**Comment by oguzkarademir** [comment]
> @oguzkarademir I am not very good at it as well. But we will learn :)

💯

**Comment by oguzkarademir** [comment]
We have some time to start writing code, I am working on `useState`, `useEffect`, `useHistory`, `useParams` and `router` concepts, I will try to make examples similar to our individual project. We will use them a lot. And React-Context concept i should look at this, thank you @dirk-jacobs

**Comment by LujiAnna** [comment]
@dirk-jacobs I hadn't read the react docs. But seems like context api doesn't completely replace redux, except when used with React Hooks. 
Okay, no need to install external libraries then. So we can go ahead with context + hooks :)

**Comment by yildiraykoyuncu** [comment]
Hey @LujiAnna Hey @oguzkarademir, so I think our user stories and prototype almost ready. Maybe we can start discussing the react components. What I think is we need to draw a diagram showing components and their relation. (Which one is inside which one etc..). Then we can divide components among us. 
What do you think?

**Comment by LujiAnna** [comment]
@yildiraykoyuncu absolutely.
I was actually thinking on the same thing. 
I wonder if there's a template/software to use for this...

**Comment by yildiraykoyuncu** [comment]
@LujiAnna I can look for a template but something very simple will do the job I think. We just need some boxes and arrows 😄

**Comment by dirk-jacobs** [comment]
Not sure if this is what you are looking for but Figma has a 'Prototyping' option
https://help.figma.com/hc/en-us/articles/360040314193-Guide-to-prototyping-in-Figma

Check it out

https://www.youtube.com/watch?v=6KdPbZnDthU

**Comment by oguzkarademir** [comment]
Guys I am leaving a youtube video [here](https://www.youtube.com/watch?v=1eO_hNYzaSc) to learn how to use React Context, and when do you available, today or tomorrow ? I am available tonight or tomorrow after 1200. We should discuss the structure and useful packages that we can use

**Comment by yildiraykoyuncu** [comment]
Hey guys, I draw a diagram for our components. Please take a look when you can. Then we can discuss it! 
For the post detail and profile components, we will add details after the prototypes are ready.

[VoxBox Components](https://drive.google.com/file/d/1BXNg4iNyUFvyLCQ4MS08GSeeTzGt_SzW/view?usp=sharing)

**Comment by LujiAnna** [comment]
[Wireframe here for reference](https://www.figma.com/file/8jXbP0Jail2bdhJj1MupYo/Volunteering-App?node-id=25%3A2)

**Comment by LujiAnna** [comment]
Looks detailed @yildiraykoyuncu . Am getting it fully open here..
@dirk-jacobs @oguzkarademir am taking a look at them .
We have a starting point for discussion on react then 🥂

**Comment by LujiAnna** [comment]
Dropped this on slack for disc today(if sth missing pls bring it up. Everything is from disq above) : 

- Structure
- Components
- Prototype
- Packages
- Resources

**Comment by LujiAnna** [comment]
Then comes along a series of sleepless nights 🤖 😄

**Comment by yildiraykoyuncu** [comment]
Guys I pushed the front-end branch, our new master, to the repo. You can fetch it to your local computers 👍

**Comment by LujiAnna** [comment]
@yildiraykoyuncu thanks!! 
Btw, I think we both need logo for ur nav and footer for me. 
I was wondering if @adekimpianna could update both logo and favicon in client/public folder to the relevant icons/logo so we can reference. 
Or there's another way to do it?

**Comment by LujiAnna** [comment]
We use [react-bootstrap](https://react-bootstrap.github.io/getting-started/introduction) & or if convenient [vanilla bootstrap](https://getbootstrap.com/docs/4.5/getting-started/download/#npm), and some sass .

**Comment by LujiAnna** [comment]
Hey guys!
We will need a documentation for front end, 
but currently I have just drafted a quick [wiki page on installation](https://github.com/gelilaa/VoxBox/wiki/Installation), if you can help me feel out what needs to be run or installed and where for things like styling or etc to showcase on client
