### ISSUE TITLE
Homepage, CTA and About us components

### ISSUE THREAD

**Issue by oguzkarademir** [gelilaa/VoxBox#52]
- [x] Create a Homepage component
- [x] Create the path of the Homepage component in App.js with React Router
- [x] Create 2 components (CTA, About Us) in Homepage component
- [x] Create a registrations button to get to the registration page in CTA component
- [x] Use React-Bootstrap package for styling

relates #15 
relates #18 
relates #19

**Comment by gelilaa** [comment]
Done!!
