### ISSUE TITLE
Backend Discussion

### ISSUE THREAD

**Issue by LujiAnna** [gelilaa/VoxBox#6]
- Tools: Node.js

**Comment by mametur** [comment]
## Road 1 (sign-up)
1. Sign up with user name, last name, password, email
2. verify the email address.
3. before query DB, prevent SQL injection.
4. check email => if the email exists in DB, then show an error message(redirect to sign-in).
-- if the user does not have an account--
5. Before storing the user password in DB, then hash and salt it.
6. Store user info in DB.
7. Send a success message to the user.

## Road 2 (sign-in)
1. Give an error for an empty field
2. if user fill all field then Authentication
3. Before authentication, prevent SQL injection.
4. if user info correct, then navigate the main page
5. if user info does not correct, give a specific error

## Road3 (forget password)
1. use a library for reset password.

**Comment by gelilaa** [comment]
hey @mametur  
# Road 3 
1. use a library for reset password..
    Do you mean the user can create a new password or can a user recover their passwords?
   (is it GET or PATCH)?

**Comment by mametur** [comment]
@gelilaa Do you mean the user can create a new password or can a user recover their passwords? recover password

**Comment by miroslavveljanoski** [comment]
Hey @mametur because I don't have experience with MySQL, if you have some good learning materials please send it to me, in order to be better prepared before we start with coding 🙄

**Comment by oguzkarademir** [comment]
> ## Road 1 (sign-up)
> 1. Sign up with user name, last name, password, email
> 2. verify the email address.
> 3. before query DB, prevent SQL injection.
> 4. check email => if the email exists in DB, then show an error message(redirect to sign-in).
>    -- if the user does not have an account--
> 5. Before storing the user password in DB, then hash and salt it.
>  #### **@mametur we can use [Bcryptjs](https://www.npmjs.com/package/bcryptjs) package to hide user password in databases**
> 6. Store user info in DB.
> 7. Send a success message to the user.
> 
> ## Road 2 (sign-in)
> 1. Give an error for an empty field
> 2. if user fill all field then Authentication
> 3. Before authentication, prevent SQL injection.
> 4. if user info correct, then navigate the main page
> 5. if user info does not correct, give a specific error
> 
> ## Road3 (forget password)
> 1. use a library for reset password.

**Comment by gelilaa** [comment]
hey back-enders @miroslavveljanoski & @mametur ,I   have found a great  tutorial on sequelize  [here](https://www.youtube.com/watch?v=pxo7L5nd1gA) please check it out 😉
