### ISSUE TITLE
Database Discussion

### ISSUE THREAD

**Issue by LujiAnna** [gelilaa/VoxBox#8]
- SQL=> Mysql

**Comment by mametur** [comment]
I would use NoSQL => It will be easy retrieve data from DB and we will have not complicated relationship between data

**Comment by mametur** [comment]
![db](https://user-images.githubusercontent.com/52838641/102483864-aa6bd400-4065-11eb-8f9b-a6778d6c58e8.png)

**Comment by dirk-jacobs** [comment]
Hi Mamé,

Can you think/discuss about the following:

- person
  - do you need an address ? (To be able to go to the person)
  - what do you mean by town ? Is it equal to city or do you mean zipcode ? (eg city==Brussels; zipcode==1000)
  - bio ? is 255 chars enough ?

- post
  - likeCount: should this be a number ?

**Comment by mametur** [comment]
@dirk-jacobs Thanks for your feedback, 
likeCount: should this be a number ? I was thinking  we can make profile strength upon the likes such as  ★★☆☆☆(100 likes=== 2 star). We will discuss it:)

do you need an address ? (To be able to go to the person)=> This will just give information about the user. It will not connect any filtering or search

what do you mean by town ? Is it equal to city or do you mean zipcode ? (eg city==Brussels; zipcode==1000)=> Yeah it can be zipcode or post code. 

bio ? is 255 chars enough ? It is not enough we can change as 500 or 1000?

**Comment by mametur** [comment]
There is also data [type text](https://dev.mysql.com/doc/refman/5.7/en/string-types.html) but I am not sure how it works?

**Comment by mametur** [comment]
@dirk-jacobs  i found this [explanation](https://dev.to/lisahjung/beginner-s-guide-to-using-mysql-database-in-a-node-js-app-49li) ,the parenthesis next to VARCHAR allows you to specify the number of characters you are willing to allow. Change the number of characters if your use case requires longer characters. **For long lines of texts, choose Text as the data type**

**Comment by miroslavveljanoski** [comment]
> @dirk-jacobs Thanks for your feedback,
> likeCount: should this be a number ? I was thinking  we can make profile strength upon the likes such as  ★★☆☆☆(100 likes=== 2 star). We will discuss it:)
> 
> do you need an address ? (To be able to go to the person)=> This will just give information about the user. It will not connect any filtering or search
> 
> what do you mean by town ? Is it equal to city or do you mean zipcode ? (eg city==Brussels; zipcode==1000)=> Yeah it can be zipcode or post code. 
> 
> bio ? is 255 chars enough ? It is not enough we can change as 500 or 1000?

**Comment by miroslavveljanoski** [comment]
Hey @mametur I'm not sure why we have likeCount in post, are we going to like the posts? As I understood I thought that we are going to leave likes on the profile of the user(volunteer), where are all the information about certain user?

**Comment by oguzkarademir** [comment]
@mametur I have a question , Will there be data related to the photograph of the user? My idea is to take user photos and store them in a cloud and save the photo url address to the database. For now i dont know how can we do that but if we can change our data schema, we can think later

**Comment by mametur** [comment]
@miroslavveljanoski  we will discuss about like icon(likeCount) when we have a meeting. It still is not clear.

**Comment by mametur** [comment]
@oguzkarademir looks nice idea but for pictures when we finish our must have user story then we can look it up for now as I know we will use some avatars.
