### ISSUE TITLE
Comments are not correctly ordered

### ISSUE THREAD

**Issue by dirk-jacobs** [gelilaa/VoxBox#90]
Would expect that comments are ordered from Newest to Oldest, but seems like there is no real order

![image](https://user-images.githubusercontent.com/63724492/104199709-0e48a900-5428-11eb-80e7-44e6cf9dc0c5.png)

**Comment by oguzkarademir** [comment]
I raised the 'Leave a comment' box and set the comment order, the last comment will be on top
